u-wave/web

src/actions/BoothActionCreators.js
src/actions/ChatActionCreators.js
src/actions/LoginActionCreators.js
src/actions/ModerationActionCreators.js
src/actions/PlaylistActionCreators.js
src/actions/UserActionCreators.js
src/actions/VoteActionCreators.js
src/actions/WaitlistActionCreators.js
src/store/request.js
src/store/socket.js
src/utils/mergeIncludedModels.js
test/reducers/playlists.js
test/reducers/roomHistory.js

goto-bus-stop/u-wave-api-v1#118

actions: update all API response handlers for new format

---

src/components/Avatar/index.css
src/components/Chat/LogMessage.js
src/components/Chat/Message.css
src/components/Chat/Message.js
src/components/Chat/index.js
src/components/FooterBar/UserInfo.css
src/components/RoomUserList/Row.js
src/components/RoomUserList/index.js
src/components/UserCard/UserCard.js
src/components/UserCard/index.css
src/components/UserCard/index.js
src/components/UserList/UserRow.css
src/components/UserList/index.css
src/components/Username/index.js
src/components/WaitList/ModRow.css
src/components/WaitList/ModRow.js
src/components/WaitList/ModRowBase.js
src/components/WaitList/Position.js
src/components/WaitList/SimpleRow.css
src/components/WaitList/SimpleRow.js
src/components/WaitList/index.js
src/components/index.css
src/utils/userCardable.js

User popovers, with just rank and join date for now.
(There's a no-op play history button in this branch ATM but will probably remove that since we don't have user profile pages yet.)
Todo:
- Mod action buttons

User popovers

---

src/components/WaitList/ModRow.css

By cutting off usernames with an ellipsis instead of wrapping them around.

waitlist: fix #445 (long usernames overflowing)

---

src/components/Chat/index.css
src/components/SidePanels/index.css
src/components/SidePanels/index.js
src/containers/Chat.js

Removes this weird bottom margin:

side-panels: make users and waitlist fill the entire panel space

---

src/components/SettingsManager/ChangeUsernameButton.js

The dialog was placed inside a button, which made it size weirdly.

settings: fix username dialog size

---

package.json

chore(package): update debug to version 2.4.1

---

package.json

chore(package): update debug to version 2.5.1

---

package.json

Not sure why Greenkeeper didn't open a PR for this yet, but CI looks good so

fix(package): update i18next to version 6.0.1

---

package.json

This one updates the peerdep to i18next@6 (#529)

chore(package): update react-i18next to version 2.0.1

---

src/components/Chat/ChatMessages.js
src/components/Chat/DeleteButton.js
src/components/Chat/Message.css
src/components/Chat/Message.js
src/components/Chat/MessageTimestamp.js
src/containers/ChatMessages.js
src/selectors/chatSelectors.js

Not sure about the colour but: ![Screenshot](http://i.imgur.com/fggmcYL.png)

chat: add Delete button to chat messages

---

src/components/Dialogs/LoginDialog/LoginForm.js

Since it doesn't do anything yet

login: Remove Forgot Password link pending #264

---

src/components/Video/index.js
src/selectors/settingSelectors.js
src/utils/chatMentions.js

Should also add shims for used ES6 features (Object.assign, ??)

Fixes for IE10

---

src/components/PlaylistManager/Panel/Meta.js

Were broken by #504. Thanks to pinkguk and maybecat for reports :pray: 
Should also look into setting up integration tests for this stuff.

playlists: Fix playlist meta actions.

---

package.json

fix(package): update material-ui to version 0.17.0

---

src/components/Dialogs/EditMediaDialog/index.js

[Webm](https://gateway.ipfs.io/ipfs/QmPLyULQtSaA2BrGTDjWSsEzXS5Qp5imYmN8hkEyABfZuH)

Add button to swap artist/title

---

src/components/Chat/ChatMessages.js
src/components/Chat/Message.js

Makes the Delete button work again for moderators, and removes it for not-moderators.

Fix deleting chat messages.

---

src/components/Chat/ChatMessages.css
src/components/Chat/ChatMessages.js
src/components/Chat/ScrollDownNotice.js

chat: Show "Back To Recent Messages" button when scrolled up.

---

locale/en.yaml
locale/nl.yaml
src/components/FooterBar/SkipButton.js
src/components/FooterBar/SkipReasonsList.js
src/components/FooterBar/index.js

When clicking the Skip button shows:

Add Skip reason selector

---

.travis.yml

Since v4 has been out for a bit.

ci: Install `latest` npm instead of v3.

---

src/containers/ChatInput.js

Oops, we were always showing the chat input.

chat: Hide chat message input when logged out

---

src/components/WaitList/ModRowBase.js
src/components/WaitList/SimpleRow.css

So you can better see where you'll drop whoever you're dragging.

waitlist: Use larger placeholder while dragging, closes #534

---

locale/en.yaml
src/components/Dialogs/LoginDialog/RegisterForm.js
src/components/Form/Button.css

login: Add Privacy Policy checkbox to register form, closes #14

---

package.json

fix(package): update material-ui to version 0.18.0

---

package.json

chore(package): update recompose to version 0.23.3

---

src/sources/youtube/Player.js
src/sources/youtube/PlayerEmbed.js

youtube: allow pausing video in Preview mode

---

src/components/Video/VideoMouseMoveCapture.js
src/components/Video/VideoProgressBar.js
src/components/Video/VideoToolbar.js
src/components/Video/index.css

Seems like our issue was caused by a bug(?) in the postcss plugin but the `@apply` proposal is not going to be spec anyway so we may as well just avoid it.

video: Remove deprecated `@apply` usage, fixes #650

---

src/components/FooterBar/Responses/Bar.css
src/components/RoomHistory/Row.css
src/components/RoomHistory/Votes.js

Room History style fixes

---

src/components/FooterBar/SkipButton.css
src/components/FooterBar/SkipButton.js
src/components/FooterBar/index.css

So there's some clear feedback when you skip someone.

Add a loading spinner to the skip button.

---

src/components/SettingsManager/LogoutButton.js

This didn't affect anything but it did log an error to the console.

Fix JS error on logout.

---

src/components/Chat/Markup/Emoji.css
src/components/Chat/Markup/Emoji.js

So you can right-click » copy URL. The alt text contains the image
shortcode, so if the image doesn't exist for some reason or you copy the
message text, it'll show/copy the shortcode instead.

chat: Use an `<img>` for emoji.

---

src/actions/ChatActionCreators.js
src/utils/playMentionSound.js

This shouldn't live in an action creators module. (Maybe it shouldn't even be used in one.)

Move playMentionSound into util module.

---

src/components/About/index.css
src/components/About/index.js
src/components/Overlay/index.js
src/components/PlaylistManager/index.css
src/components/PlaylistManager/index.js
src/components/RoomHistory/index.css
src/components/RoomHistory/index.js
src/components/SettingsManager/index.css
src/components/SettingsManager/index.js
src/containers/About.js
src/containers/PlaylistManager.js
src/containers/RoomHistory.js
src/containers/SettingsManager.js

Small change so the animating parts of overlays are separate from the non-animating content.

Make overlays standalone components, not tied to <Overlay/>

---

src/store/socket.js

Ref https://github.com/u-wave/api-v1/pull/147

Ignore WebSocket keepalive messages.

---

tasks/serve.js

So we only use it in watch mode.

build: Decide whether to use autoreloading API server later

---

src/components/Dialogs/EditMediaDialog/index.js
src/components/FooterBar/Eta.js
src/components/MediaList/Row.js

Pass correct units to format-duration.

---

.babelrc.js
test/.eslintrc.json
test/components/ErrorArea/index.js
test/mocha.opts
test/sources/youtube/Player.js
test/utils/mergeIncludedModels.js

- Add some tests
- Add code coverage

Work on tests

---

src/components/SettingsManager/ChangeUsernameButton.js

Only send name change request if new name is different.

---

src/index.html

force most modern rendering engine

Add x-ua-compatible meta tag for IE

---

src/app.js

So that error reporting libraries can report this stuff.

Rethrow boot errors.

---

package.json

instead of doing this sequence by hand, type `npm run prerelease`

build: Add prerelease npm script

---

package-lock.json
package.json

update react-i18next to version 6.0.4

---

package-lock.json
package.json
src/index.html
src/password-reset.html
webpack.config.js

Adds hashes for files so the browser can check that the file it
downloaded is the one the html file asked for.

Implement subresource integrity

---

src/middleware.js

This would allow a client app to use this config.

Expose client config as JSON

---

src/components/AddToPlaylistMenu/PlaylistsMenu.js
src/components/FooterBar/SkipReasonsList.js

For compatibility with recent material-ui.

Remove last onTouchTap references.

---

src/actions/SearchActionCreators.js
src/components/PlaylistManager/Menu/Row.css
src/components/PlaylistManager/Menu/SearchResultsRow.js
src/components/PlaylistManager/Menu/index.js
src/constants/actionTypes/search.js
src/containers/PlaylistManagerMenu.js
src/reducers/mediaSearch.js
src/reducers/playlists.js

when pressing the close button, the search results are deleted and the _active_ playlist is selected.

Implement closing search results, fixes #74

---

src/utils/commands/playback.js

Use `/playback off` to disable media playback. Use `/playback on` to enable it.

Add /playback chat command to toggle media playback.

---

package-lock.json
package.json
src/components/Chat/ChatMessages.js
src/components/Chat/Input/index.js
src/containers/App.js
src/containers/ChatInput.js
src/containers/ChatMessages.js

using react-bus to communicate between ChatInput and ChatMessages. this way we don't have to store scroll position in state which would be super difficult.

Scroll chat when pressing PageUp/PageDown in chat input, fixes #44

---

src/components/DialogCloseAnimation/index.js

This was causing the web client to crash when folks changed their
username.

Fix dialog close animation

---

src/components/Video/index.js

Fixes an issue where the fullscreen video progress bar was still being
shown after exiting fullscreen.

Fix fullscreen change detection

---

src/components/FooterBar/index.css

Removes the horizontal compression on other elements when the next song title is very long.

Stiffen footer bar.

---

src/locale.js

Avoids like one tick of work in i18next, don't think it matters much on the client but if you do a server render it does 🤷‍♀️

Synchronously add English language strings to i18next resources.

---

package-lock.json
package.json
src/store/request.js

Switch to qs-stringify

---

locale/en.yaml
src/components/SettingsManager/NotificationSettings.js
src/reducers/settings.js
src/selectors/chatSelectors.js

For consistency with other notification types.

Add setting for skip notifications in chat.

---

src/actions/PlaylistActionCreators.js
src/components/MediaList/Actions/MoveToLast.js
src/components/PlaylistManager/Panel/index.js
src/containers/PlaylistManagerPanel.js
src/reducers/playlists.js
test/reducers/playlists.js

The first playlist item gets a button to move it down to the end. Depends https://github.com/u-wave/http-api/pull/178.

Add button to move first item to end of playlist, fixes #435

---

src/components/HeaderBar/Slider.js
src/components/HeaderBar/Volume.js

I could not get it to crash again with this, I think it was probably related to the event typo fix.

Slider fixes

---

src/components/App/index.css

Fixes the serif fonts in dialogs.

Apply fonts and colour styles to the body instead of to `.App`.

---

src/components/FatalError/index.css
src/components/FatalError/index.js
src/components/index.css
src/containers/App.js

(error message here is "Testing a thing!")

Show crash message + reload instruction on error.

---

src/mobile/components/MainView/index.css

Fix mobile AppBar height.

---

gulpfile.js
tasks/serve.js

Makes `gulp js:babel` a bit less slow.

Lazy load webpack config.

---

src/Uwave.js
src/app.js
src/sources/soundcloud/index.js
src/sources/youtube/index.js

Instead always use the sourceType specified by the source plugin.
Similar to https://github.com/u-wave/core/pull/153.

Remove custom sourceType parameter.

---

src/components/Dialogs/PreviewMediaDialog/index.js

Allow focusing chat when PreviewMediaDialog is open.

---

src/admin/actions/users.js
src/admin/components/AdminApp/index.css
src/admin/components/UsersList/Header.css
src/admin/components/UsersList/Header.js
src/admin/components/UsersList/Row.css
src/admin/components/UsersList/Row.js
src/admin/components/UsersList/index.css
src/admin/components/UsersList/index.js
src/admin/constants/ActionTypes.js
src/admin/containers/UsersList.js
src/admin/reducers/users.js
src/admin/selectors/userSelectors.js
src/utils/formatJoinDate.js

- Only show the primary role for space reasons
- Only show join date, not time, for space reasons
- Larger font so it's easier to read
- Fix paddings
- Implement pagination
- Implement filters (depends on server updates)

Some work on the admin user overview

---

src/components/Form/Button.css
src/components/Form/Button.js
src/components/PlaylistManager/Menu/NewPlaylist.js
src/components/PlaylistManager/Menu/PlaylistImportRow.js
src/components/PlaylistManager/Menu/Row.css
src/components/PlaylistManager/Menu/Row.js
src/components/PlaylistManager/Menu/SearchResultsRow.js
src/components/PlaylistManager/Menu/index.js

So we can get material-ui's keyboard focus handling, accessibility
(hopefully), and some pretty effects too.

Replace some components with material-ui versions.

---

src/password-reset/containers/PasswordResetApp.js

Oops, currently that page isn't working at all...

Fix theme related crash on password reset page.

---

src/components/Dialogs/LoginDialog/RegisterForm.js
src/components/ReCaptcha/index.js

Also doesn't add the global recaptcha callback if it's not used.

Wait for recaptcha response before enabling Register button.

---

src/admin/components/Motd/index.js

Use an HTML form for the MOTD update UI.

---

src/components/HeaderBar/Slider.js

This removes some unnecessary animations so it feels less sluggish,
fixes the crash issue at the source, and fixes some keyboard controls.

Update Slider from the material-ui PR

---

src/components/MediaList/Actions.css
src/components/MediaList/Actions/Action.js

So they get the same hover effects and keyboard stuff as the other
buttons.

Use material-ui IconButtons for media actions.

---

locale/en.yaml
src/sources/soundcloud/Player.css
src/sources/soundcloud/Player.js

It looks horrendous but the implementation works:

soundcloud: Show error message if track cannot be loaded.

---

locale/en.yaml
src/components/PlaylistManager/Panel/NoSearchResults.js
src/components/PlaylistManager/Panel/SearchResults.css
src/components/PlaylistManager/Panel/SearchResults.js

 Show a message if a search turned up no results. 

---

src/components/About/index.css
src/components/ServerList/index.css
src/components/ServerList/index.js
src/components/index.css

- Center the loading spinner.
- Avoid horizontal scrollbar.

Fix server list sizing.

---

src/mobile/components/Video/index.js
src/sources/soundcloud/Player.css

Mobile SoundCloud player fixes

---

src/components/PlaylistManager/Panel/Meta.css
src/components/PlaylistManager/Panel/Meta.js

- Make the "Activate" text clickable
- Show pointer cursor on hover
- Set "disabled" on the checkbox if playlist is already active (removes
pointer cursor)

Fixes for playlist "Active" checkbox.

---

src/components/PlaylistManager/Menu/index.js
src/components/RoomUserList/index.js

Fixes the little black rectangle above the user list here:

Disable vertical padding in user and playlist lists.

---

src/reducers/playlists.js

Fix crash in playlists reducer when not signed in.

---

package-lock.json
package.json
src/Uwave.js
src/components/Chat/ChatMessages.js
src/components/DialogCloseAnimation/index.js
src/components/Dialogs/LoginDialog/LoginForm.js
src/components/Dialogs/LoginDialog/RegisterForm.js
src/components/Dialogs/LoginDialog/ResetPasswordForm.js
src/components/FooterBar/index.js
src/components/Video/index.js
src/containers/App.js
src/polyfills.js

This will show warnings about things that are not safe in React's async rendering mode (not yet enabled).

 Enable React Strict Mode. 

---

src/reducers/chat.js
src/selectors/chatSelectors.js

Don't try to parse it if it doesn't exist.

Fix null MOTD.

---

src/mobile/components/DrawerMenu/index.css
src/mobile/components/UsersDrawer/index.css

Add a min-width to mobile drawers.

---

src/components/Chat/Input/index.css
src/components/FooterBar/index.css

Remove top border from footer bar.

---

src/components/FooterBar/index.css

- Add a hover effect like on the settings button.
- Set cursor to `pointer`.

Make the footer bar playlist toggle more obviously a button.

---

src/components/FooterBar/Responses/Button.css
src/components/FooterBar/SkipButton.css
src/components/FooterBar/index.css
src/components/HeaderBar/HistoryButton.css
src/components/HeaderBar/Volume.css
src/components/HeaderBar/index.css
src/components/Overlay/Header/Close.css
src/components/Overlay/Header/index.css
src/components/Overlay/Header/index.js
src/components/PlaylistManager/Panel/Meta.css
src/components/Video/index.css
src/theme.js

Now they're all(?) the same size. I didn't figure out how to remove the ripple yet tho.

Consistentify icon buttons

---

src/components/Dialogs/PreviewMediaDialog/index.css
src/components/Dialogs/PreviewMediaDialog/index.js

Remove title and padding from PreviewMediaDialog.

---

src/components/FooterBar/WaitlistButton.css
src/components/FooterBar/WaitlistButton.js
src/components/FooterBar/index.css
src/components/FooterBar/index.js

Also moving the CSS for the WL button into its own file.

Add margin to the waitlist button icon.

---

src/components/HeaderBar/AppTitle.css

A bit more margin to the right and a height of 32px.

Tweak logo size.

---

src/sources/soundcloud/PreviewPlayer.js

Otherwise it's a tiny little square.

soundcloud: Use same size as YouTube for preview player.

---

src/mobile/components/PlaylistManager/PlaylistPanel.js

oops forgot
It needs some buttons or something so you can actually search but this is a start

Add the "This playlist is empty" to mobile.

---

src/components/Chat/ChatMessages.css
src/components/Chat/Message.css
src/utils/createTheme.js
src/vars.css

- Removes alternating backgrounds.

Simplify chat message styles.

---

src/app.js
src/password-reset/app.js
src/utils/readApplicationConfig.js

It was not parsing the config JSON from the script tag, only loading it
as a string.

Fix loading client config on Password Reset page.

---

locale/en.yaml
src/components/PlaylistManager/Panel/PlaylistFilterEmpty.js
src/components/PlaylistManager/Panel/index.js

Add "No results" panel instead of "empty" when playlist filter does not match anything.

---

src/components/Dialogs/LoginDialog/SocialLogin.js

Save some kB that is rarely needed.

Lazy load google signin button.

---

src/components/Dialogs/PromptDialog/index.js

Fixes nickname changes.
Fixes creating playlists.

Fix returning value from PromptDialog.

---

src/reducers/__tests__/votes.js
src/reducers/votes.js

Regression introduced by #1103
Also adding some tests for this behaviour.

Clear votes again on advance.

---

package-lock.json
package.json

 Update uglifyjs-webpack-plugin to the latest version 🚀 

---

package-lock.json
package.json

fix(package): update debug to version 4.0.1

---

package-lock.json
package.json
webpack.config.js

It works with webpack 4 again!

build: Add common-shake

---

package-lock.json
package.json

fix(package): update react-markdown to version 4.0.

---

package-lock.json
package.json

chore(package): update autoprefixer to version 9.3.1

---

package-lock.json
package.json

Update material-ui to the latest version

---

package-lock.json
package.json

chore(package): update css-loader to version 2.0.2

---

package-lock.json
package.json
test/common.js

Use a more minimal and up to date package

yamlify → yaml-hook

---

package-lock.json
package.json
tasks/webpack/compileDependencies.js

It uses fancy new JS features.

deps: update escape-string-regexp

---

src/components/SidePanels/PanelContainer.js

This will tell React that rendering these is low priority.

Set hidden=true on invisible tabs.

---

src/admin/containers/AdminApp.js
src/components/AdminProxy/index.js

It was still using the old style react-redux context, but that's not
supported anymore.

Fix loading the admin panel

---

src/components/Player/index.js
src/components/Video/Player.js
src/components/Video/index.js
src/context/MediaSourceContext.js

Time to use this project as React.js practice before contract work again :joy: :ok_hand:

Rewrite Video components using hooks

---

package-lock.json
package.json
src/components/Dialogs/PromptDialog/__tests__/index.js
test/common.js

```
TypeError: activeElement.attachEvent is not a function
at startWatchingForValueChange (/home/travis/build/u-wave/web/node_modules/react-dom/cjs/react-dom.development.js:3321:17)
at handleEventsForInputEventPolyfill (/home/travis/build/u-wave/web/node_modules/react-dom/cjs/react-dom.development.js:3363:5)
at Object.extractEvents (/home/travis/build/u-wave/web/node_modules/react-dom/cjs/react-dom.development.js:3462:7)
at extractEvents (/home/travis/build/u-wave/web/node_modules/react-dom/cjs/react-dom.development.js:697:44)
at runExtractedEventsInBatch (/home/travis/build/u-wave/web/node_modules/react-dom/cjs/react-dom.development.js:731:16)
at handleTopLevel (/home/travis/build/u-wave/web/node_modules/react-dom/cjs/react-dom.development.js:4476:5)
```

Add a test for #1090

---

locale/en.yaml
locale/nl.yaml
src/components/PlaylistManager/Header/SearchBar.js
src/components/PlaylistManager/Header/index.js
src/components/PlaylistManager/Import/ImportSourceBlock.js
src/components/PlaylistManager/NoPlaylists.js
src/components/PlaylistManager/NoPlaylists/ImportBlock.js
src/components/PlaylistManager/NoPlaylists/index.css
src/components/PlaylistManager/NoPlaylists/index.js
src/components/PlaylistManager/Panel/index.css
src/components/PlaylistManager/index.css
src/components/PlaylistManager/index.js
src/components/SearchBar/index.js
src/components/SettingsManager/LogoutButton.js
src/containers/PlaylistManager.js

An idea for when you first open the playlists menu:
When done, this will screw with the tutorial on wlk.yt

Add intro screen if user has no playlists

---

src/components/AddToPlaylistMenu/PlaylistsMenu.js
src/components/AddToPlaylistMenu/index.js

Rewrite AddToPlaylistMenu using hooks

---

package-lock.json
package.json
src/admin/containers/AdminApp.js
src/hooks/useIntl.js

Update react-redux to 7.1

---

package-lock.json
package.json
tasks/webpack/compileDependencies.js

p-finally is an async function and crashed prod builds.

Support async functions in dependencies

---

package-lock.json
package.json
src/components/HeaderBar/Volume.js
webpack.config.js

It was moved into core from lab.

Use Slider component from material-ui core.

---

src/components/RoomUserList/index.js
src/utils/isDraggingNearTopOfRow.js

Remove uses of ReactDOM.findDOMNode.

---

src/middleware/index.js
tasks/serve.js

Reduces I/O when serving these pages.

Cache contents of HTML templates.

---

.eslintrc.json
package-lock.json
package.json

Closes https://github.com/u-wave/web/issues/1321.

Use babel-eslint v11 beta.

---

.travis.yml

ci: re-enable eslint
