u-wave/web

- src/actions/BoothActionCreators.js
- src/actions/LoginActionCreators.js
The new api response format returns an empty object instead of a `null` for empty booths, so we need to check whether the object we receive actually contains any booth data before using it.
> booth: fix dealing with empty booth objects (rather than nulls)

- src/store/socket.js
Property was wrongly named ¯\_(ツ)_/¯
> socket: fix removing chat messages by id

- .eslintignore
- .gitignore
- src/index.html
- src/middleware.js
- tasks/browserify.js
- tasks/clean-css.js
- tasks/clean-js.js
- tasks/compile-css.js
- tasks/copy-assets.js
- tasks/copy-html.js
- tasks/watch.js
Only files that should be accessible in the browser go in public/. Babelified JS files still go in lib/. This prevents eg. https://welovekpop.club/middleware.js
> build: put compiled & bundled files in public/ instead of lib/

- src/components/App/index.css
normalize.css v5 changed the default font for buttons and some other interactive elements. this reverts it to the old behaviour so inputs and buttons use Open Sans again.
> style: use global font on buttons too (like normalize.css v4.2)

- src/utils/userCardable.js
"Cardable" elements (i.e., that get a user card attached when click) use `<span>`s which means that cardable elements with block contents (e.g. a `<div>`) would lose their height. This trips up react-list, because it looks at the height of its children to compute how many items it needs to show. With an inline `<span>` as the first child, the height of eg. the first User row appears to be 0, whereas it should be 40.
Changing it to a `<div>` ensures the cardable element takes on the size of its contents.
> users: wrap cardable elements in <div>s to maintain height

- src/sources/youtube/Player.css
- src/sources/youtube/PlayerEmbed.js
This forces the video to play immediately when it pauses, instead of making the elements non-clickable. This way you can still right-click the video to get the URL or drag it (360° videos).
> youtube: use less intrusive way to prevent clicks from pausing YT player

- package.json
- src/utils/Promise.js
- tasks/browserify.js
- tasks/watch.js
Simplifies the build a bit more. youtube-player v3.0.5 and on don't depend on Bluebird anymore.
> remove bluebird-removing hacks. youtube-player uses native promises now

- package.json
- tasks/js.js
Now built JS files in es/ and lib/ import or require JavaScript modules with translations, instead of YAML files. To import or require YAML files, build tools usually need plugins (like yamlify or yaml-loader or rollup-plugin-yaml ...). By shipping JS modules for the translations instead server owners don't have to add a YAML plugin to their custom build process, and it'll still Just Work™.
> build: convert yaml files to js modules for custom build use

- src/components/Chat/LogMessage.js
- src/components/Chat/Markup/GroupMention.js
- src/components/Chat/Message.js
- src/components/Chat/Motd.js
Marks message components as pure so the entire contents of all old
messages aren't reconciled when a new message comes in.
> chat: improve message receive performance

- middleware.js
- package.json
Changes the entry point so the client can be bundled with an ES
module bundler. `import Uwave from 'u-wave-web'` now imports the
main client class, while
`import createWebClient from 'u-wave-web/middleware'` imports the
server-side client-serving (lol) middleware. Previously, the
client class would have to be accessed through `u-wave-web/lib/Uwave`.
> change module entry point

- src/components/FooterBar/Responses/Bar.css
- src/components/FooterBar/Responses/Bar.js
- src/components/FooterBar/Responses/Button.js
- src/components/FooterBar/Responses/Downvote.js
- src/components/FooterBar/Responses/Favorite.js
- src/components/FooterBar/Responses/Upvote.js
- src/components/FooterBar/index.js
Makes things not-clickable.
[WIP] because this breaks tooltips somewhat, the `onMouseLeave` event that's used to hide tooltips isn't always fired correctly. Not sure if that's on our end or on React's :scream:
> footer: disable vote buttons when current user is DJ or booth is empty, fixes #452

- src/Uwave.js
- src/actions/OverlayActionCreators.js
- src/components/About/index.css
- src/components/About/index.js
- src/components/App/index.js
- src/components/HeaderBar/AppTitle.css
- src/components/HeaderBar/AppTitle.js
- src/components/HeaderBar/index.css
- src/components/HeaderBar/index.js
- src/components/index.css
- src/containers/About.js
- src/containers/App.js
- src/containers/HeaderBar.js
Adds a user-fillable overlay, to be accessed by:
Server hosts can register a React component that will be rendered in the overlay using a plugin script.
```js
import * as React from 'react';
uw.setAboutPageComponent(
class MyAboutPage extends React.Component {
render() {
return 'hoi';
}
}
);
```
> about: add about page overlay

- src/middleware.js
- tasks/serve.js
Pulls a trick on webpack-dev-middleware to allow our middleware to serve the HTML file instead. Fixes emoji in dev mode.
> build: inject config to html in watch mode

- src/components/Chat/Markup/Emoji.js
- src/components/Chat/index.css
- src/components/FooterBar/Responses/Button.js
- src/components/Tooltip/index.css
- src/components/Tooltip/index.js
- src/components/index.css
Moves the somewhat hacky manual tooltip positioning from emoji and vote buttons into a separate component. The new component also repositions the tooltip if it is very close to the window border. I.e., if a `center`-aligned tooltips appears near the right edge of the screen, it'll become a `left`-aligned one instead.
> tooltips: add repositioning tooltip wrapper, fix overflow bug in emoji tooltips

- .babelrc
- package.json
Cuts a few bytes off the prod build and is faster. inline-elements checks the syntax and switches to a faster method instead of react's own `createElement` when possible (which is almost always). Probably won't make a big difference, but why not ¯\_(ツ)_/¯
> build: add react-inline-elements transform in production build.

- src/components/SidePanels/PanelTemplate.js
- src/components/SidePanels/index.js
- src/components/Tabs/Tab.js
- src/components/Tabs/TabTemplate.js
- src/components/Tabs/index.js
Thin wrapper around material-ui's Tabs with default styles that fit in. All of this was in the SidePanels component first but mostly unrelated to its purpose, so now it's a reusable component.
> Add Tabs component with üWave-friendly styling

- tasks/js.js
Not exactly sure how the modules get out of sync, but I've had it a few times with lib/middleware.js. The middleware wouldn't recompile because es/middleware was up to date.
> build: Fix recompiling es/ and lib/ dirs if es/ is up-to-date but lib/ is not

- src/components/PlaylistManager/Header/SearchBar.js
- src/components/PlaylistManager/Header/index.js
- src/components/PlaylistManager/Import/index.css
- src/components/PlaylistManager/Menu/index.js
- src/components/PlaylistManager/Panel/index.css
- src/components/PlaylistManager/index.css
- src/components/PlaylistManager/index.js
- src/containers/MediaSearchBar.js
- src/containers/PlaylistManager.js
- src/containers/PlaylistManagerMenu.js
- src/containers/PlaylistManagerPanel.js
- src/containers/SearchResultsPanel.js
- src/selectors/playlistSelectors.js
- src/selectors/searchSelectors.js
Makes the PlaylistManager less of a massive monstrosity and will also make it easier to move the smaller containers around in the future.
> Split up PlaylistManager into smaller containers, fixes #349

- src/components/Chat/Message.css
Before/After:
Emoji would render on top of chat timestamps and delete buttons.
This change instead renders the timestamps and delete buttons on
top.
> chat: Fix chat timestamps appearing behind emoji.

- src/components/Chat/Input/EmojiSuggestion.css
- src/components/Chat/Input/EmojiSuggestion.js
- src/components/Chat/Input/index.css
Emoji that aren't squares are stretched a bit weirdly in the suggestions list:
When they're supposed to be centered vertically and horizontically, with maintained aspect ratio:
This changes the emoji suggestions to use a CSS background with size `contain`, just like emoji in chat messages already do.
> chat: Fix squeezed display of non-square emoji in suggestions list.

- src/components/Chat/ChatMessages.css
- src/components/Chat/ChatMessages.js
- src/components/Chat/LogMessage.js
- src/components/Chat/Message.css
- src/components/Chat/Message.js
These patches change two things that could cause the entire chat message list to rerender every time a new message was received.
The chat delete button handlers for moderators are now not recreated each time the list rerenders, so no longer cause all chat messages to rerender too.
I removed the striped chat message display (maybe will add it back with a CSS-only solution later) because it caused all chat messages to switch their `alternate` classname when 1) a message is deleted or 2) a new message comes in whilst there are already 512 messages in scrollback. Now it looks like:
Which honestly is not that bad :thinking: but I'll see if the stripes can work well using _just_ CSS.
> Chat performance fixes

- src/components/Chat/Input/index.js
Otherwise a few emoji with longer names could drown out suggestions for a shorter emoji name, and the shorter name would always have to be typed out completely.
> chat: Sort emoji autocomplete suggestions by length, closes #532

- package.json
- webpack.config.js
Also changes one use of Lodash's implicit _.property wrapping.
The lodash Webpack plugin removes unused lodash features. Need to try this out a bit more first to make sure we're not using any of the features that are being removed.
Lodash 5.x will disable most or all of those features by default so it's good to make sure we're not using any of them now.
> build: add Lodash Webpack plugin

- src/utils/mergeIncludedModels.js
- webpack.config.js
Bit of a follow-up to #512.
We used the lodash dotted path `a.b.c` functionality in
`mergeIncludedModels`, so enable it again in the lodash
webpack plugin.
Also changes one use of `find` with a matcher object to a function.
Also uses the Lodash Webpack plugin everywhere, instead of just in
the production build, so it becomes easier to catch these problems
in development.
> build: Enable lodash paths.

- src/components/Video/index.js
- src/sources/soundcloud/Player.js
- src/sources/youtube/Player.js
Using the blurred thumbnail as a background is a very good default, so no reason to make individual sources responsible for it.
> video: Always render VideoBackdrop regardless of current media source.

- src/components/Dialogs/LoginDialog/RegisterForm.js
- src/components/ReCaptcha/ReCaptcha.js
- tasks/serve.js
> Use ReCaptcha's Dark theme

- webpack.config.js
Fixes a few warnings when building üWave Web:
```
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
```
> Update extract-text-webpack-plugin usage.

- src/store/request.js
Fixes #554
The favorite action for new playlists relied on the playlist object
being returned from `createPlaylist`, but it was instead returning
the raw HTTP response. This patch uses the result from request
`onComplete` handlers if possible.
> request: Resolve HTTP requests with return value from onComplete

- src/components/Video/VideoBackdrop.js
Removes our only use of `dangerouslySetInnerHtml`.
> video: Use React to generate SVG video backdrop.

- src/components/ReCaptcha/index.js
- src/containers/App.js
- src/utils/timed.js
This way only components that are actually in the DOM will be able to have side effects.
While I don't think we'll want to support server side rendering explicitly (since it's pretty useless for a heavily interactive application like this), this way we'll at least not fire requests or start timers if you _do_ try to render it on the server.
See https://github.com/facebook/react/issues/7671
> Remove side effects from componentWillMount

- src/components/PlaylistManager/Panel/index.js
- src/components/PlaylistManager/index.js
- src/reducers/playlists.js
Makes switching playlists a bit nicer.
Playlists that are still loading now don't show a big loading spinner, but show the media rows it will have, similar to what unloaded pages already look like while scrolling down.
Also drive-by fixes #519.
> Show cached playlist items when switching playlists instead of waiting for them to reload.

- src/MuiTheme.js
- src/Uwave.js
- src/actions/ChatActionCreators.js
- src/actions/LoginActionCreators.js
- src/sources/soundcloud/Player.js
- src/sources/youtube/PlayerEmbed.js
- src/store/configureStore.js
- src/store/socket.js
- src/utils/ChatCommands.js
- test/common.js
Removes the last few `require` calls from the üWave source.
Earlier some `require` calls were just leftovers, and the mention sound was included through a `require` call inside an `if` so it won't be included when running tests. Now I manually insert a JS module into the require cache, so it uses that instead when running tests.
> Use `import` everywhere

- package.json
- tasks/utils/renderLoadingScreen.js
- tasks/utils/renderMarkdown.js
- Update Babel loader to the beta, which uses an up-to-date version of `loader-utils`.
- Set the userAgent used for build-time rendering of markdown and the loading spinner to "all" (used by material-ui for vendor prefixing CSS).
This way the webpack output is 100% clean
> Fix some warning output in Webpack build

- webpack.config.js
A bunch of packages still use the older `jsnext:main` convention to list ES-modules entry points in their `package.json` files.
> build: Add `jsnext:main` to entry point fields.

- src/components/Loader/CircularProgress.css
- src/components/Loader/CircularProgress.js
- src/components/Loader/index.css
- src/components/Loader/index.js
Like this:
This spinner was adapted from material-ui@v1.x's CircularProgress. We use material-ui@v0.x atm but its CircularProgress requires javascript for its animation, and the one in v1.x is CSS-only. That's useful because we show the spinner on the loading screen before the JS is loaded in.
> Use a material-ui-like loading spinner.

- src/components/Avatar/index.js
It's the same thing as sigil.cupcake.io but with an üWave name on it.
> Default to `https://sigil.u-wave.net` avatars.

- src/sources/soundcloud/Player.css
- src/sources/soundcloud/Player.js
- src/sources/soundcloud/SongInfo.css
- src/sources/soundcloud/SongInfo.js
> Truncate long song names in SoundCloud card, fixes #407.

- src/markdown.css
- static/privacy.md
Now the üWave logo fits in better with the header text.
> privacy: Fix logo size.

- tasks/serve.js
This adds the üWave Web Client middleware _before_ the webpack dev middleware, so our middleware will be able to serve the `index.html` and inject config before the dev middleware gets to.
> Small `serve` task cleanup

- package.json
- tasks/serve.js
This is especially useful for mongodb because they didn't use to show anything at all if the connection failed, the web api would just not respond
> build: Show more helpful Redis/Mongo connection errors

- src/Uwave.js
- src/app.js
- src/index.html
Currently you see the app without any users etc for a few ms before the /now state loads in. This patch defers the first actual render of the app until the /now state is available.
> Wait for state from /now before rendering

- src/middleware.js
Never ended up using this. This way was quite limited since you need to be able to change components to do most useful things and that wasn't possible in a custom JS file that runs after the main app. We've just used a fork for custom stuff on https://welovekpop.club/ so far and I think that's the simplest way to keep doing it for now … I don't have a good alternative extensibility system in mind.
> middleware: Remove old experimental plugin file code

- src/actions/TickerActionCreators.js
This does add a whole tonne of logic to the timers but if your computer clock changes for some reason (timezone change, synced with a time server, or whatever) üWave will now resync its clock with the server time.
> Resync time if the local clock changes unexpectedly.

- src/components/MediaList/Row.css
- src/components/MediaList/Row.js
- src/components/MediaList/index.js
- src/components/RoomHistory/Row.css
This means the same dom element is used for the same media row as long as it's in view, so when you scroll it's not just the contents being moved.
> Use a unique key for media list rows.

- src/components/HeaderBar/Progress.js
UglifyJS was removing the property access because it didn't think it did
anything. Now using a method call instead, which is not removed (at
least at the moment, heh)
> progress: Fix progress bar animation in prod build

- .babelrc
- .babelrc.js
- .travis.yml
- package-lock.json
- package.json
- postcss.config.js
- webpack.config.js
`babel-preset-latest` will be deprecated in favour of `babel-preset-env`. This PR switches to `-env` and prepares for a few more upcoming Babel changes, and takes the opportunity to add some `babel-preset-env` related features to the build.
Babel 7 will probably support .babelrc.js files, for now I pointed our `.babelrc` to use `.babelrc.js` as a preset. It doesn't use Babel's `env` option anymore but instead checks the target environment manually.
This removes Babel hacks from `webpack.config.js`.
You can now specify a `BROWSERSLIST` environment var in development mode to enable only the transforms you need in your dev environment, to speed up compilation. Eg:
```
BROWSERLIST="firefox 51" npm start
```
Will not compile `class`es, for example. It also applies to CSS. However for CSS, …
> Use babel-preset-env and .babelrc.js

- src/components/MediaList/index.js
Now if all loaded items in a media list are identical, it keeps the selection.
> Remember playlist item selection as new pages are loaded, fixes #648

- src/actions/PlaylistActionCreators.js
- src/components/PlaylistManager/Panel/Meta.js
- src/components/PlaylistManager/Panel/ShufflePlaylistButton.js
- src/reducers/playlists.js
Fixes #413.
`shufflePlaylist` now only resolves when the playlist items have also been reloaded.
> Add loading spinner to and move reload into shuffle operation.

- src/components/Chat/NotificationMessages/UserNotificationMessage.js
The `<Interpolate />` component requires a parent component to be wrapped in `translate()`.
> fix interpolation in chat notifications

- src/Uwave.js
- src/containers/App.js
- src/locale.js
Fixes an issue where the chat would show `chat.userJoin` on load sometimes because the locale promise only resolved later.
> Wait for locale to be loaded before rendering anything.

- src/components/HeaderBar/Volume.js
- src/utils/commands/index.js
- src/utils/commands/playback.js
- src/utils/commands/users.js
Adding a few commands so it's easier to do mundane things without needing a mouse.
Should add commands for enable/disable media playback, fullsize video, maybe more
> More chat commands

- tasks/js.js
The babel build script for the lib/ and es/ folders rewrites imports for locale .yaml files to refer to compiled .js files, so it's possible to `require()` them. I broke this in #609, as most locale .yaml files are now loaded using `import('x')` calls rather than `import x from 'x'` statements.
> build: Fix locale import paths in lib/ and es/

- locale/en.yaml
- package-lock.json
- package.json
- src/actions/LoginActionCreators.js
- src/components/Dialogs/LoginDialog/ResetPasswordForm.js
- src/middleware.js
- src/password-reset.html
- src/password-reset/actions.js
- src/password-reset/app.css
- src/password-reset/app.js
- src/password-reset/components/PasswordResetPage/index.css
- src/password-reset/components/PasswordResetPage/index.js
- src/password-reset/components/PasswordResetSuccessPage/index.js
- src/password-reset/constants.js
- src/password-reset/containers/PasswordResetApp.js
- src/password-reset/index.html
- src/password-reset/reducers.js
- tasks/apiServer.js
- webpack.config.js
Client-side part of u-wave/api#89.
This adds a new app entry point under the `src/password-reset` folder. This app only renders a form to enter a new password.
The development server logs password reset email contents to the console.
> Implement password reset page

- src/Uwave.js
Webpack would rewrite the `accept` callback to a normal function,
breaking the `this` binding.
> Fix HMR rerendering (work around webpack bug I guess?)

- src/sources/youtube/PlayerEmbed.js
The force-play-on-pause code was calling `playVideo` even when we explicitly called `stopVideo` because the next media was on a different media source. This didn't use to be a problem, I think the old YT player didn't emit the pause event when `stopVideo` was called. Anyway, this only unpauses the video if the current media is from YouTube, which fixes the problem.
> youtube: Fix previous video restarting in the background when switching media source

- .travis.yml
- package-lock.json
- package.json
- src/Uwave.js
- src/locale.js
- tasks/utils/jsonLoader.js
- webpack.config.js
Saves a decent amount of bytes in the output by tree-shaking CommonJS modules, in addition to Webpack's tree-shaking of ES modules.
Replaces `es6-promise` with `lie` which has the same functionality but does not use `require()` in a way that makes common-shake bail out.
> build: Add common-shake.

- src/components/UserCard/index.js
Leaves a little margin at the bottom so the it'll definitely fit on the next calculation.
A better fix would be to only call `fitInsideWindow` if the current update was not triggered by `setState`… may switch this PR to do that later on
> Fix UserCards opening slowly near window edge.

- package-lock.json
- package.json
- src/components/Chat/Markup/Link.js
This one's a bit smaller and faster. This way we don't include the node
url and querystring modules anymore.
Like #771 but `shorten-url` does keep the `https?://` scheme in front.
> deps: truncate-url → shorten-url

- src/store/socket.js
We were trying to send the authentication token to the socket whenever the `LOGIN_COMPLETE` action came in, even if it was a failed login. In that case we would send `undefined` and mark the authentication as complete, so once a login attempt was successful, we would not send the correct token.
> socket: Ignore `error` actions, fixes #775.

- locale/en.yaml
- src/actions/BoothActionCreators.js
- src/components/Chat/ChatMessages.js
- src/components/Chat/NotificationMessages/SkipMessage.js
- src/components/Chat/specialMessages.js
- src/constants/actionTypes/booth.js
- src/reducers/chat/notifications.js
- src/store/socket.js
If a reason is given, it's shown in the message. just as a single word though, not as a nice string. might be possible to add that since the nice strings are in the language files for use in the skip reason list.
the dj's name is not clickable if the dj was skipped by a moderator, this might be possible later but it's kinda hard right now.
> Implement skip notifications

- src/components/Chat/ChatMessages.css
Ensure it shows up on top of chat messages instead of behind them.
> Fix "Scroll to Bottom" button visibility, fixes #792

- src/components/Loader/CircularProgress.css
- src/components/Loader/CircularProgress.js
Taking it from the next version of material-ui again.
It looks weird now (like there are two lines circling around) so need to check out where my copy paste job went wrong.
> Fix progress spinner in Firefox

- tasks/utils/loadStaticHtmlTemplate.js
> Strip HTML from static markdown page titles.

- package-lock.json
- package.json
- src/middleware.js
- Use hstream instead of trumpet. it is faster and more concise.
- Gzip dynamic responses too. looks like 50%+ size savings when using emojione. The main thing taking up space in the html is emoji definitions in the client config.
> Optimize html responses

- src/components/HeaderBar/AppTitle.css
- src/components/HeaderBar/AppTitle.js
- src/components/HeaderBar/index.css
- src/components/HeaderBar/index.js
So we can swap our long horizontal WE ♥ KPOP logo for the squarish S3 one. This removes some hardcoded pixel sizes and instead uses flexbox for the top bar. It reserves space for the logo, volume bar and history button, and lets the current song title take up the rest.
Changed the logo to be a real `<img />` instead of a background image, this way it will take up space in the flexbox layout without having to give a hardcoded width and height to the tag.
> Adapt top bar to logo size

- src/components/App/Overlays.js
Instead, ensure that the previous one is unmounted, and the new one is
mounted, by setting a `key` on the transition.
> Fix overlays diffing internally when switching between them

- src/actions/TickerActionCreators.js
- src/components/ClockProvider/index.js
- src/containers/App.js
Makes the app container deal with fewer things, and makes the clock
stuff reusable in other client frontends.
> Extract second timer from App container.

- src/components/UserList/UserRow.css
material-ui expects these elements to be `display: flex` instead.
> Fix vote icon alignment in user rows.

- src/components/AddToPlaylistMenu/PlaylistsMenu.js
Previously this event handler was on the Menu component, where material-ui@0.x gave it the clicked item. Now it is not so we have to pass the playlist ID in manually.
> Fix favouriting into existing playlist.

- src/components/HeaderBar/Slider.js
- src/reducers/settings.js
The page would crash if the volume was changed to something > 100%, because the SoundCloud and YouTube players don't accept values that high. Of course it should not be possible to change the volume to >100%, but sometimes the slider did it anyway. That's what we get for copy pasting code from a WIP upstream PR :)
This fixes crashes in situations where the volume would be changed from <100% to >100%
- Moving the slider all the way to the right
- Unmuting when the volume is >100%
- Closing a preview dialog when the volume is >100%
> Fix crashes when volume is way up

- src/sources/soundcloud/PreviewPlayer.js
It's already included and makes this bit a bit nicer :woman_shrugging:
> Use qs-stringify to simplify building the soundcloud embed URL.

- webpack.config.js
Forgot to update this in the earlier PR.
> Fix alias for ES modules version of material-ui icons.

- src/components/FooterBar/Responses/Bar.css
- src/components/FooterBar/Responses/Button.css
- src/components/FooterBar/Responses/Button.js
- src/components/FooterBar/Responses/index.css
The wrapping divs that are used to allow the Tooltip to listen to hover
events were causing the buttons to be smaller.
> Fix ResponseButtons not covering the full FooterBar height.

- src/components/LazyOverlay/index.css
- src/components/LazyOverlay/index.js
- src/components/Overlay/index.css
- src/components/index.css
- src/containers/PlaylistManager.js
- src/containers/RoomHistory.js
- src/containers/SettingsManager.js
Only load the necessary code once the Settings, Playlist Manager, or Room History panels are opened. 
Would be cool to add more parts of the desktop UI here later so we can have a smaller mobile bundle (takes some time to run the almost 1MB of unzipped code on mobile)
> Lazy load overlay code.

- .babelrc.js
I accidentally set this to the wrong value. We don't need the the
runtime to use polyfills here.
Saves a few kB after compression. Gains will be even better when
dependencies start switching to Babel 7 too.
> Fix @babel/runtime useBuiltIns configuration.

- src/mobile/containers/Video.js
- src/selectors/boothSelectors.js
Seems like very few mobile apps have a slider. This patch changes the
mobile video to only have to volume states: on (100%) and off (0%). It
defaults to on.
Can add a mute button to the vote buttons overlay once that's back.
> Play media on full volume on mobile, fixes #878.

- locale/en.yaml
- src/sources/soundcloud/Player.css
- src/sources/soundcloud/Player.js
Does this when the song can't be played automatically:
It's not necessary for YouTube because it'll show up in a paused state with a working Play button already.
> soundcloud: Request user interaction if autoplay is blocked

- src/mobile/components/DrawerMenu/index.css
- src/mobile/components/DrawerMenu/index.js
- src/mobile/components/UsersDrawer/index.css
- src/mobile/components/UsersDrawer/index.js
- src/mobile/components/index.css
Previously if you had a really long playlist name, the drawer could be
wider than the screen. Now playlist names are truncated at 90% of the
viewport width.
> Add max width to mobile drawers.

- src/components/FooterBar/NextMedia.css
Only matters when zooming in I guess
> Prevent playlist name wrapping on narrow screens.

- src/mobile/components/DrawerMenu/index.js
- src/mobile/components/UsersDrawer/index.js
The `PaperProps` className was overriding the classNames added by the
Drawer. Drawer also exposes a `classes.paper` prop which does what we
need without conflicts.
> Fix mobile UsersDrawer docking to the left.

- src/components/Player/index.js
- src/mobile/components/Video/index.css
- src/mobile/components/Video/index.js
- src/sources/soundcloud/Player.js
- src/sources/youtube/Player.js
- src/sources/youtube/PlayerEmbed.js
So people can tap to start playing, and then tap again to see vote
buttons.
> Enable mobile vote button area once media is playing.

- src/Uwave.js
`matchMedia()` returns an object so this was always passing.
> Fix desktop preload check.

- package-lock.json
- package.json
- tasks/utils/htmlMinifierOptions.js
- tasks/webpack/analyze.js
- tasks/webpack/compileDependencies.js
- tasks/webpack/compress.js
- tasks/webpack/staticPages.js
- webpack.config.js
This should make the base config a bit easier to understand. 9 out of 10 times you don't need to change how static pages work, so its dozens of lines of hacks were usually in the way.
> Split some of the hacky webpack parts into separate files

- src/Uwave.js
- src/utils/createGenerateClassName.js
- src/utils/generateClassName.js
- tasks/utils/prerender.js
Fixes #967
The TabIndicator is not assigned a name in its `withStyles()` call. This
patch defaults to `ComponentN` as the component name for such components.
> Fix CSS className generation for anonymous components

- src/components/Dialogs/PromptDialog/index.js
PromptDialogs call `onSubmit` with the input value inside their
`handleSubmit` methods, but also pass all `props` including `onSubmit`
through to their `<Dialog />` instance. This was causing `onSubmit` to
be called twice; once by `handleSubmit`, and once by the Dialog. The
Dialog calls it with a synthetic events instance, causing errors down
the line.
This patch prevents `onSubmit` being passed to the Dialog.
> Fix duplicate `onSubmit` calls in PromptDialog.

- src/components/App/Overlays.js
- src/components/Overlay/index.css
This makes them faster. Now, the .Overlay-body element is the one being
animated.  The .Overlay element sets `overflow-y: hidden` to prevent a
scrollbar when transitioning elements are halfway off the page.
> Use transforms for overlay transitions.

- locale/en.yaml
- src/components/Chat/ChatMessages.css
- src/components/Chat/ScrollDownNotice.js
This also fixes an issue where the button would keep showing even
after the button was no longer keyboard-focused.
> Animate scroll down button in and out on keyboard focus.

- src/components/HeaderBar/HistoryButton.css
- src/components/HeaderBar/HistoryButton.js
- src/components/HeaderBar/index.css
The `Header` part is not relevant.
> Rename HeaderHistoryButton → HistoryButton.

- locale/en.yaml
- src/components/FooterBar/SettingsButton.css
- src/components/FooterBar/SettingsButton.js
- src/components/FooterBar/index.css
- src/components/FooterBar/index.js
- src/components/SettingsManager/SettingsPanel.js
So you can change playback settings and the like when you're not signed in.
I moved the auth buttons to the right because they looked weird otherwise, now it's like this:
> Add settings button when signed out

- locale/en.yaml
- src/components/PlaylistManager/NoPlaylists.js
- src/components/PlaylistManager/Panel/PlaylistEmpty.css
- src/components/PlaylistManager/Panel/PlaylistEmpty.js
- src/components/PlaylistManager/Panel/index.css
- src/components/PlaylistManager/Panel/index.js
- src/components/PlaylistManager/index.js
the message is not _that_ helpful but I didn't want it to wrap even on small screens :/ At least it's better than a totally black area.
>  Add a screen for empty playlists. 

- postcss.config.js
- src/actions/ThemeActionCreators.js
- src/app.js
- src/components/Chat/Input/Suggestion.css
- src/components/Chat/Message.css
- src/components/FooterBar/WaitlistButton.css
- src/components/LazyOverlay/index.css
- src/components/MediaList/Row.css
- src/components/Overlay/index.css
- src/components/PlaylistManager/Menu/index.css
- src/components/PlaylistManager/Panel/index.css
- src/components/RoomHistory/index.css
- src/components/SettingsManager/index.css
- src/constants/ActionTypes.js
- src/constants/actionTypes/theme.js
- src/containers/App.js
- src/demo.js
- src/experimentalThemePlugin.js
- src/reducers/theme.js
- src/selectors/settingSelectors.js
- src/sources/soundcloud/Player.css
- src/theme.js
- src/utils/createTheme.js
- src/vars.css
In modern browsers with CSS variable support, variables are defined in JavaScript based on the material-ui theme. This theme can be made to be customisable in the future. In browsers lacking CSS variable support, they will fall back to the default theme.
There is a console API that you can use to change the theme at runtime. `uw.debugApplyTheme()` merges an object into the material-ui theme [(this one)](https://github.com/u-wave/web/blob/master/src/theme.js) and `uw.debugResetTheme()` reverts to the default theme.
This monstrosity, for example, is the result of a few `uw.debugApplyTheme()` calls:
There are most likely some hardcoded values left, but this is a start. At least it makes the existing variables configurable :)
> Use CSS variables for theming.

- package-lock.json
- package.json
Includes a ton of tooltip improvements. It now only mounts tooltips in the DOM when they are visible, so it's safe to add hundreds of them (may be useful for media actions or something).
> Update material-ui to v1.4.

- src/components/Dialogs/EditMediaDialog/index.js
- src/components/Dialogs/LoginDialog/index.js
- src/components/Dialogs/PreviewMediaDialog/index.js
They now use `DialogCloseAnimation` instead of material-ui's `open` prop.
The DialogCloseAnimation allows the contained Dialog to unmount completely, while animating out in its final state. This is especially useful for the login, edit, and preview dialogs, which are managed using Redux—their internal state is reset when they animate out. Previously, this would cause some jerkiness. The login dialog reverted to the Login form, even if you were on the Register or Password Forgot form; the edit and preview dialogs unmounted their contents without animating before fading out. Now, the most recent state is kept for the duration of the animation and then discarded.
> Refactor login, edit, preview dialogs.

- src/components/ClockProvider/index.js
When the callback list is changed, use the new one.
Fixes the timestamps in the footer bar and the history list.
> Fix timers.

- src/reducers/votes.js
Fixes the vote counters always being 0 on load, even if people already
voted.
Previously this was handled via the ADVANCE action, but the stats were
removed from it a while ago. That was because the stats were only
available on the initial ADVANCE, not subsequent ones, which was
inconsistent.
Now it uses the INIT_STATE action which is more appropriate.
> Initialize votes on load

- src/reducers/playlists.js
Previously, switching between playlists would result in the filter menu being hidden and the filter applying. However the playlist item count used for scrolling was the unfiltered amount. Scrolling down would show loading icons for all non matching items.
There is still a bug where clicking the selected playlist will keep the filter menu open while showing unfiltered items, but that's not as bad.
> Clear filter when selecting a different playlist.

- webpack.config.js
This way nginx can be configured to serve it, so static files don't have
to be served by node.
> Build static hashed filenames into a /static/ folder.

- package-lock.json
- package.json
- src/actions/LoginActionCreators.js
- src/store/socket.js
Replaces reconnecting-websocket with custom logic. Now, when reconnecting, we first hit /now to get the socket token. This also syncs state, which should fix the crashes we get after reconnecting after a long time—usually because a user left in the mean time, but local out-of-date state still had them in the waitlist, or because someone joined in the mean time and sent a chat message, but local state doesn't know who they are.
> New reconnect logic

- src/actions/LoginActionCreators.js
- src/reducers/booth.js
- src/reducers/votes.js
Fixes some more initial booth vote issues, and reduces the amount of store churn during the initial load.
> Use INIT_STATE action for initial booth setup.

- src/reducers/booth.js
Regression introduced by #1128, didn't test it well enough.
Now merges the media object from /now in the same way that it's merged on the `advance` socket event.
This is a bit messy tbh but it's a very breaking bug and this fixes it
so it'll have to do.
> Fix initialising current song on load

- src/components/App/index.css
- src/markdown.css
- src/utils/createTheme.js
- src/vars.css
There was actually a difference between the font-family declarations in the CSS and the ones used for material-ui components. This fixes it.
> Take CSS font-family value from the material-ui theme.

- package.json
- test/mocha.opts
mocha.opts is not supported in v6, so just use CLI args.
> Fix mocha options.

- package.json
Since we don't depend on it anymore anyway.
> Remove react-i18next from greenkeeper ignore list

- webpack.config.js
not sure why these weren't working in CJS, but the ES versions do.
> Fix react-dnd imports in prod mode.

- package-lock.json
- package.json
- src/components/Chat/ChatMessages.js
- src/components/FooterBar/index.js
- src/components/LazyOverlay/index.js
- src/components/PlaylistManager/Panel/DeletePlaylistButton.js
- src/components/PlaylistManager/Panel/Meta.css
- tasks/serve.js
Fixes all but two of the remaining React/material-ui warnings. Just DialogCloseAnimation remaining, and something inside react-transition-group that is outside of our control.
> Reduce Concurrent Mode warnings

- package-lock.json
- package.json
- src/containers/App.js
- src/reducers/settings.js
It was only still used for some indirection that didn't really help readability anyways. I think our top level component will just have to be a mountain of `<Provider>` elements
> Remove recompose.

- .travis.yml
mostly so we can temporarily disable linting, which is broken at the moment
> ci: refactor matrix

- src/utils/commands/waitlist.js
`args` is an array so would always evaluate to true. We want to use the
default message if no message parameters were given.
> Fix default message for forced DJ skips.

- src/components/MediaList/index.css
This CSS is no longer necessary since we switched to `react-window`.
> Fix double scrollbar in media lists

- src/reducers/__tests__/playlists.js
- src/reducers/playlists.js
Selectors figure out which playlist is selected by looking at the
separate `selectedPlaylistID` property.
> Remove unused `.selected` property from playlists
